# pandas practice1
온라인 쇼핑몰 주문 데이터를 다루는 실습이다.

범위:
- intro
- indexing_edit
- io
- preprocessing

규칙:
- 각 문제 아래 코드 셀에서 직접 풀기
- 필요한 경우 셀을 추가해도 된다
- 파일 저장은 현재 작업 폴더 기준으로 진행한다

## 0. 시작 데이터 만들기

In [68]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    '주문번호': ['O001', 'O002', 'O003', 'O004', 'O005', 'O006', 'O006', 'O008'],
    '주문일자': ['2026-01-03', '2026-01-05', '2026-01-05', '2026-01-08', '2026-01-10', '2026-01-12', '2026-01-12', '2026-01-15'],
    '고객명': ['김철수', '이영희', '박민수', '최지영', '정다은', '홍길동', '홍길동', '강민호'],
    '지역': ['서울', '부산', '서울', '대전', None, '부산', '부산', '서울'],
    '카테고리': ['전자', '식품', '전자', '패션', '식품', '전자', '전자', '패션'],
    '상품명': ['노트북', '사과', '마우스', '자켓', '우유', '키보드', '키보드', '운동화'],
    '수량': [1, 10, 2, 1, np.nan, 1, 1, 2],
    '단가': [1500000, 3000, 25000, 120000, 2500, 50000, 50000, 90000],
    '결제상태': ['완료', '완료', '완료', '취소', '완료', '완료', '완료', '완료']
})
orders

   주문번호        주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태
0  O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료
1  O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료
2  O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료
3  O004  2026-01-08  최지영   대전   패션   자켓   1.0   120000   취소
4  O005  2026-01-10  정다은  NaN   식품   우유   NaN     2500   완료
5  O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
6  O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
7  O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료

## 1. 기본 확인
1) orders의 shape를 확인하시오.
2) columns를 확인하시오.
3) 상위 3행을 확인하시오.

In [69]:
print(orders.shape)
print()
print(orders.columns)
print()
display(orders.head(3))

(8, 9)

Index(['주문번호', '주문일자', '고객명', '지역', '카테고리', '상품명', '수량', '단가', '결제상태'], dtype='str')

   주문번호        주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태
0  O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료
1  O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료
2  O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료

## 2. 열 선택
1) 고객명 열만 선택하시오.
2) 상품명, 수량, 단가 열만 선택하시오.

In [70]:
print(orders["고객명"])
print()
display(orders[["상품명", "수량", "단가"]])

0    김철수
1    이영희
2    박민수
3    최지영
4    정다은
5    홍길동
6    홍길동
7    강민호
Name: 고객명, dtype: str

   상품명    수량       단가
0  노트북   1.0  1500000
1   사과  10.0     3000
2  마우스   2.0    25000
3   자켓   1.0   120000
4   우유   NaN     2500
5  키보드   1.0    50000
6  키보드   1.0    50000
7  운동화   2.0    90000

## 3. 인덱싱
주문번호를 인덱스로 설정한 새로운 DataFrame df를 만들고 아래를 수행하시오.
1) O003 행 전체를 loc으로 조회
2) 첫 번째 행을 iloc으로 조회
3) O002의 단가를 at으로 조회

In [94]:
df = pd.DataFrame({
    '주문일자': ['2026-01-03', '2026-01-05', '2026-01-05', '2026-01-08', '2026-01-10', '2026-01-12', '2026-01-12', '2026-01-15'],
    '고객명': ['김철수', '이영희', '박민수', '최지영', '정다은', '홍길동', '홍길동', '강민호'],
    '지역': ['서울', '부산', '서울', '대전', None, '부산', '부산', '서울'],
    '카테고리': ['전자', '식품', '전자', '패션', '식품', '전자', '전자', '패션'],
    '상품명': ['노트북', '사과', '마우스', '자켓', '우유', '키보드', '키보드', '운동화'],
    '수량': [1, 10, 2, 1, np.nan, 1, 1, 2],
    '단가': [1500000, 3000, 25000, 120000, 2500, 50000, 50000, 90000],
    '결제상태': ['완료', '완료', '완료', '취소', '완료', '완료', '완료', '완료']
},index=['O001', 'O002', 'O003', 'O004', 'O005', 'O006', 'O006', 'O008'],)

df.index.name = ('주문번호')
display(df)
print()
# 1) O003 행 전체를 loc으로 조회
print(f'1) O003 행 전체를 loc으로 조회\n', df.loc['O003'])
print()
# 2) 첫 번째 행을 iloc으로 조회
print(f'2) 첫 번째 행을 iloc으로 조회\n', df.iloc[1])
print()
# 3) O002의 단가를 at으로 조회
print(f'3) O002의 단가를 at으로 조회\n', df.at['O002', '단가'])

            주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태
주문번호
O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료
O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료
O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료
O004  2026-01-08  최지영   대전   패션   자켓   1.0   120000   취소
O005  2026-01-10  정다은  NaN   식품   우유   NaN     2500   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료

1) O003 행 전체를 loc으로 조회
 주문일자    2026-01-05
고객명            박민수
지역              서울
카테고리            전자
상품명            마우스
수량             2.0
단가           25000
결제상태            완료
Name: O003, dtype: object

2) 첫 번째 행을 iloc으로 조회
 주문일자    2026-01-05
고객명            이영희
지역              부산
카테고리            식품
상품명             사과
수량            10.0
단가            3000
결제상태            완료
Name: O002, dtype: object

3) O002의 단가를 at으로 조회
 3000

## 4. 조건 필터링
1) 결제상태가 완료인 행만 조회하시오.
2) 카테고리가 전자이고 단가가 30000 이상인 행만 조회하시오.
3) 지역이 서울 또는 부산인 행만 조회하시오.

In [95]:
df = pd.DataFrame({
    '주문일자': ['2026-01-03', '2026-01-05', '2026-01-05', '2026-01-08', '2026-01-10', '2026-01-12', '2026-01-12', '2026-01-15'],
    '고객명': ['김철수', '이영희', '박민수', '최지영', '정다은', '홍길동', '홍길동', '강민호'],
    '지역': ['서울', '부산', '서울', '대전', None, '부산', '부산', '서울'],
    '카테고리': ['전자', '식품', '전자', '패션', '식품', '전자', '전자', '패션'],
    '상품명': ['노트북', '사과', '마우스', '자켓', '우유', '키보드', '키보드', '운동화'],
    '수량': [1, 10, 2, 1, np.nan, 1, 1, 2],
    '단가': [1500000, 3000, 25000, 120000, 2500, 50000, 50000, 90000],
    '결제상태': ['완료', '완료', '완료', '취소', '완료', '완료', '완료', '완료']
},index=['O001', 'O002', 'O003', 'O004', 'O005', 'O006', 'O006', 'O008'],)

df.index.name = ('주문번호')
df
print()
# 1) 결제상태가 완료인 행만 조회
display(f'1) 결제상태가 완료인 행만 조회', df[df['결제상태'] == '완료'])
print()
# 2) 카테고리가 전자이고 단가가 30000 이상인 행만 조회
display(f'2) 카테고리가 전자이고 단가가 30000 이상인 행만 조회', df[(df['카테고리'] == '전자') & (df['단가'] >= 30000)])
print()
# 3) 지역이 서울 또는 부산인 행만 조회
display(f'3) 지역이 서울 또는 부산인 행만 조회', df[df['지역'].isin(['서울','부산'])])

'1) 결제상태가 완료인 행만 조회'

            주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태
주문번호
O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료
O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료
O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료
O005  2026-01-10  정다은  NaN   식품   우유   NaN     2500   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료

'2) 카테고리가 전자이고 단가가 30000 이상인 행만 조회'

            주문일자  고객명  지역 카테고리  상품명   수량       단가 결제상태
주문번호
O001  2026-01-03  김철수  서울   전자  노트북  1.0  1500000   완료
O006  2026-01-12  홍길동  부산   전자  키보드  1.0    50000   완료
O006  2026-01-12  홍길동  부산   전자  키보드  1.0    50000   완료

'3) 지역이 서울 또는 부산인 행만 조회'

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태
주문번호
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료

## 5. 값 수정
1) 결제상태가 취소인 행의 수량을 0으로 수정하시오.
2) 지역이 결측치인 행의 지역을 '미상'으로 수정하시오.

In [110]:
df = pd.DataFrame({
    '주문일자': ['2026-01-03', '2026-01-05', '2026-01-05', '2026-01-08', '2026-01-10', '2026-01-12', '2026-01-12', '2026-01-15'],
    '고객명': ['김철수', '이영희', '박민수', '최지영', '정다은', '홍길동', '홍길동', '강민호'],
    '지역': ['서울', '부산', '서울', '대전', None, '부산', '부산', '서울'],
    '카테고리': ['전자', '식품', '전자', '패션', '식품', '전자', '전자', '패션'],
    '상품명': ['노트북', '사과', '마우스', '자켓', '우유', '키보드', '키보드', '운동화'],
    '수량': [1, 10, 2, 1, np.nan, 1, 1, 2],
    '단가': [1500000, 3000, 25000, 120000, 2500, 50000, 50000, 90000],
    '결제상태': ['완료', '완료', '완료', '취소', '완료', '완료', '완료', '완료']
},index=['O001', 'O002', 'O003', 'O004', 'O005', 'O006', 'O006', 'O008'],)

df.index.name = ('주문번호')
print(df)
print()
# 1) 결제상태가 취소인 행의 수량을 0으로 수정
df.loc[df['결제상태'] == '취소', '수량'] = 0
df

# 2) 지역이 결측치인 행의 지역을 '미상'으로 수정
df['지역'] = df['지역'].fillna('미상')
df

            주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태
주문번호
O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료
O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료
O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료
O004  2026-01-08  최지영   대전   패션   자켓   1.0   120000   취소
O005  2026-01-10  정다은  NaN   식품   우유   NaN     2500   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태
주문번호
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료
O004  2026-01-08  최지영  대전   패션   자켓   0.0   120000   취소
O005  2026-01-10  정다은  미상   식품   우유   NaN     2500   완료
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료

## 6. 파생 열 추가
총액 열을 추가하시오.
총액 = 수량 * 단가

In [139]:
df = pd.DataFrame({
    '주문일자': ['2026-01-03', '2026-01-05', '2026-01-05', '2026-01-08', '2026-01-10', '2026-01-12', '2026-01-12', '2026-01-15'],
    '고객명': ['김철수', '이영희', '박민수', '최지영', '정다은', '홍길동', '홍길동', '강민호'],
    '지역': ['서울', '부산', '서울', '대전', None, '부산', '부산', '서울'],
    '카테고리': ['전자', '식품', '전자', '패션', '식품', '전자', '전자', '패션'],
    '상품명': ['노트북', '사과', '마우스', '자켓', '우유', '키보드', '키보드', '운동화'],
    '수량': [1, 10, 2, 1, np.nan, 1, 1, 2],
    '단가': [1500000, 3000, 25000, 120000, 2500, 50000, 50000, 90000],
    '결제상태': ['완료', '완료', '완료', '취소', '완료', '완료', '완료', '완료']
},index=['O001', 'O002', 'O003', 'O004', 'O005', 'O006', 'O006', 'O008'],)

df.index.name = ('주문번호')
print(df)
print()
# 총액 열을 추가하시오. 총액 = 수량 * 단가
df['총액'] = df['수량'] * df['단가']
df

            주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태
주문번호
O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료
O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료
O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료
O004  2026-01-08  최지영   대전   패션   자켓   1.0   120000   취소
O005  2026-01-10  정다은  NaN   식품   우유   NaN     2500   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료
O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료

            주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료  1500000.0
O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료    30000.0
O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료    50000.0
O004  2026-01-08  최지영   대전   패션   자켓   1.0   120000   취소   120000.0
O005  2026-01-10  정다은  NaN   식품   우유   NaN     2500   완료        NaN
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료    50000.0
O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료   180000.0

## 7. 입출력
1) 현재 DataFrame을 orders_raw.csv로 저장하시오. 인덱스는 저장하지 마시오.
2) 저장한 파일을 다시 읽어 orders_csv 변수에 담고 상위 2행을 확인하시오.

In [140]:
# 1) 현재 DataFrame을 orders_raw.csv로 저장하시오. 인덱스는 저장하지 마시오.
df.to_csv('orders_raw.csv', index=False, encoding='utf-8-sig')

# 2) 저장한 파일을 다시 읽어 orders_csv 변수에 담고 상위 2행을 확인하시오.
df_csv = pd.read_csv('orders_raw.csv')
print(df_csv.head(2))

         주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태         총액
0  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료  1500000.0
1  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료    30000.0

## 8. 결측값 확인
1) 열별 결측값 개수를 확인하시오.
2) 결측값이 하나라도 있는 행만 조회하시오.

In [141]:
# 1) 열별 결측값 개수를 확인
print(df.isna().sum())

# 2) 결측값이 하나라도 있는 행만 조회
display(df[df.isna().any(axis=1)])

주문일자    0
고객명     0
지역      1
카테고리    0
상품명     0
수량      1
단가      0
결제상태    0
총액      1
dtype: int64

            주문일자  고객명   지역 카테고리 상품명  수량    단가 결제상태  총액
주문번호
O005  2026-01-10  정다은  NaN   식품  우유 NaN  2500   완료 NaN

## 9. 결측값 처리
1) 수량 결측치는 1로 채우시오.
2) 지역 결측치는 '미상'으로 채우시오.
처리 결과를 orders_clean 변수에 저장하시오.

In [142]:
# 1) 수량 결측치는 1로 채우시오.
df['수량'] = df['수량'].fillna(1)
display(df)

# 2) 지역 결측치는 '미상'으로 채우시오.
df['지역'] = df['지역'].fillna('미상')
display(df)

# 처리 결과를 orders_clean 변수에 저장하시오.
orders_clean = df.copy()
orders_clean

            주문일자  고객명   지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O001  2026-01-03  김철수   서울   전자  노트북   1.0  1500000   완료  1500000.0
O002  2026-01-05  이영희   부산   식품   사과  10.0     3000   완료    30000.0
O003  2026-01-05  박민수   서울   전자  마우스   2.0    25000   완료    50000.0
O004  2026-01-08  최지영   대전   패션   자켓   1.0   120000   취소   120000.0
O005  2026-01-10  정다은  NaN   식품   우유   1.0     2500   완료        NaN
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동   부산   전자  키보드   1.0    50000   완료    50000.0
O008  2026-01-15  강민호   서울   패션  운동화   2.0    90000   완료   180000.0

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료  1500000.0
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료    30000.0
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료    50000.0
O004  2026-01-08  최지영  대전   패션   자켓   1.0   120000   취소   120000.0
O005  2026-01-10  정다은  미상   식품   우유   1.0     2500   완료        NaN
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료   180000.0

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료  1500000.0
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료    30000.0
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료    50000.0
O004  2026-01-08  최지영  대전   패션   자켓   1.0   120000   취소   120000.0
O005  2026-01-10  정다은  미상   식품   우유   1.0     2500   완료        NaN
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료   180000.0

## 10. 중복값 처리
1) 중복 행 개수를 확인하시오.
2) 중복 행을 제거한 결과를 orders_unique 변수에 저장하시오.

In [143]:
# 1) 중복 행 개수를 확인
display(df[df.duplicated()])

# 2) 중복 행을 제거한 결과를 orders_unique 변수에 저장
orders_unique = df.copy()
orders_unique

            주문일자  고객명  지역 카테고리  상품명   수량     단가 결제상태       총액
주문번호
O006  2026-01-12  홍길동  부산   전자  키보드  1.0  50000   완료  50000.0

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료  1500000.0
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료    30000.0
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료    50000.0
O004  2026-01-08  최지영  대전   패션   자켓   1.0   120000   취소   120000.0
O005  2026-01-10  정다은  미상   식품   우유   1.0     2500   완료        NaN
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료   180000.0

## 11. 정렬
orders_unique를 기준으로
1) 단가 내림차순 정렬
2) 카테고리 오름차순, 단가 내림차순 정렬을 수행하시오.

In [144]:
# 1) 단가 내림차순 정렬
display(orders_unique.sort_values('단가', ascending=False))

# 2) 카테고리 오름차순, 단가 내림차순 정렬
display(orders_unique.sort_values(['카테고리', '단가'],ascending=[True, False]))

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료  1500000.0
O004  2026-01-08  최지영  대전   패션   자켓   1.0   120000   취소   120000.0
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료   180000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료    50000.0
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료    30000.0
O005  2026-01-10  정다은  미상   식품   우유   1.0     2500   완료        NaN

            주문일자  고객명  지역 카테고리  상품명    수량       단가 결제상태         총액
주문번호
O002  2026-01-05  이영희  부산   식품   사과  10.0     3000   완료    30000.0
O005  2026-01-10  정다은  미상   식품   우유   1.0     2500   완료        NaN
O001  2026-01-03  김철수  서울   전자  노트북   1.0  1500000   완료  1500000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O006  2026-01-12  홍길동  부산   전자  키보드   1.0    50000   완료    50000.0
O003  2026-01-05  박민수  서울   전자  마우스   2.0    25000   완료    50000.0
O004  2026-01-08  최지영  대전   패션   자켓   1.0   120000   취소   120000.0
O008  2026-01-15  강민호  서울   패션  운동화   2.0    90000   완료   180000.0

## 12. 타입 변환
orders_unique의 주문일자 열을 datetime으로 변환하시오.

In [145]:
orders_unique.dtypes

orders_unique['주문일자'] = pd.to_datetime(orders_unique['주문일자'])
print(orders_unique.dtypes)

주문일자    datetime64[us]
고객명                str
지역                 str
카테고리               str
상품명                str
수량             float64
단가               int64
결제상태               str
총액             float64
dtype: object

## 13. 최종 확인
전처리가 끝난 orders_unique에서 필요한 열만 골라 final_orders 변수에 저장하시오.
선택 열: 주문일자, 고객명, 지역, 카테고리, 상품명, 수량, 단가, 총액, 결제상태

In [146]:
final_orders= orders_unique[['주문일자', '고객명', '지역', '카테고리', '상품명', '수량', '단가', '총액', '결제상태']]
final_orders

           주문일자  고객명  지역 카테고리  상품명    수량       단가         총액 결제상태
주문번호
O001 2026-01-03  김철수  서울   전자  노트북   1.0  1500000  1500000.0   완료
O002 2026-01-05  이영희  부산   식품   사과  10.0     3000    30000.0   완료
O003 2026-01-05  박민수  서울   전자  마우스   2.0    25000    50000.0   완료
O004 2026-01-08  최지영  대전   패션   자켓   1.0   120000   120000.0   취소
O005 2026-01-10  정다은  미상   식품   우유   1.0     2500        NaN   완료
O006 2026-01-12  홍길동  부산   전자  키보드   1.0    50000    50000.0   완료
O006 2026-01-12  홍길동  부산   전자  키보드   1.0    50000    50000.0   완료
O008 2026-01-15  강민호  서울   패션  운동화   2.0    90000   180000.0   완료